version: '3.3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"